inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - db/migrate/**
    - db/schema.rb

Rails:
  Enabled: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 180

# False positive in cap DSL
Style/FileName:
  Exclude:
    - 'config/deploy/*.rb'

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
