sudo: required
services:
  - docker

language: ruby
rvm:
  - 2.3.4 # deployed

jdk:
  - oraclejdk8

email: false

before_install:
  - docker pull suldlss/workflow-server:latest
  - docker run -d -p 127.0.0.1:3001:3000 suldlss/workflow-server:latest
  - docker ps -a
before_script:
  - bin/rails db:test:prepare
script: bundle exec rake ci
after_script:
- bundle exec codeclimate-test-reporter

sudo: false
cache: bundler
