language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
jdk:
  - oraclejdk8
email: false
before_script:
  - if [[ -r /etc/hosts ]]; then cat /etc/hosts ; fi
  - cp config/database.yml.example config/database.yml
  - bundle exec rails generate argo:solr
# - bundle exec rails generate blacklight_hierarchy:install
script: bundle exec rake ci
sudo: false
