language: ruby
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
jdk:
  - oraclejdk8
email: false
before_script:
  - bundle exec rails generate argo:solr
  - bundle exec rails generate blacklight_hierarchy:install
script: rake ci
