development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8984/solr/argo-test" %>
test: &test
  adapter: solr
  url: <%= ENV['TEST_SOLR_URL'] || "http://127.0.0.1:8984/solr/argo-test" %>
